pointfreeco/pointfreeco

Sources/PointFree/Routes.swift
Tests/PointFreeTests/LaunchSignupTests.swift
Tests/PointFreeTests/SiteMiddlewareTests.swift
Tests/PointFreeTests/__Snapshots__/LaunchSignupTests/testHome_SuccessfulSignup.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/LaunchSignupTests/testSignup.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithWWW.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithWWW.2.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithoutHeroku.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithoutHeroku.2.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithoutWWW.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithoutWWW.2.Conn.txt

redirects hosts that are not in an allow list to `www.pointfree.co`

Redirect related domains

---

Styleguide.playground/Contents.swift

This playground was out of date! It should build now.
Would be nice to automate testing around these things, but it's not an easy thing by default.

Fix Styleguide playground

---

Sources/PointFree/LaunchSignup/Views.swift

* Changed intro to read as one sentence
* Put open sourced on GitHub on it's own line
* Added built with Swift (kiiinda cool?)
* Tweaked font sizes
* Adjusted tweet copy

Adjusted some of the CSS and copy

---

Sources/PointFree/LaunchSignup/LaunchSignup.swift

When I thought this _didn't_ work I was just confused how breakpoints work lol. So this does work!

Fire and forget the send email work.

---

.gitignore
Makefile
Sources/PointFree/.env
Sources/PointFree/EnvVars.swift
Sources/PointFree/Environment.swift

We don't really need it here. We want it in pointfree-server.

Remove .env logic from PointFree

---

Package.resolved
Package.swift
Sources/Styleguide/DesignSystems/Typography.swift
Sources/Styleguide/PointFreeBaseStyles.swift
Sources/Styleguide/TODO.swift

These things now exist in `swift-web`

Remove some todos

---

.circleci/config.yml
.sourcery-templates/RoutePartialIsos.stencil
Makefile
Sources/PointFree/RoutePartialIsos.generated.swift
Sources/PointFree/Routes.swift

We've already got sourcery in the build process, might as well use it!

Code gen the route partial isos

---

Sources/PointFree/Auth.swift
Sources/PointFree/Database.swift
Sources/PointFree/Environment.swift
Sources/PointFree/GitHub.swift
Sources/PointFree/RoutePartialIsos.generated.swift
Sources/PointFree/Routes.swift
Sources/PointFree/SiteMiddleware.swift
Tests/PointFreeTests/AuthTests.swift
Tests/PointFreeTests/TestCase.swift

This is a stab at reorganizing how the app environment holds onto side-effecting logic.

Modularize side effect interfaces

---

Sources/PointFree/TODO.swift

Trying to figure out if I can write a test, but may just merge as-is

This API doesn't exist on linux

---

Package.resolved
Package.swift
Sources/PointFree/About.swift
Sources/PointFree/Account/Account.swift
Sources/PointFree/Account/Cancel.swift
Sources/PointFree/Account/Invite.swift
Sources/PointFree/Account/PaymentInfo.swift
Sources/PointFree/Account/Team.swift
Sources/PointFree/Account/UpdateProfile.swift
Sources/PointFree/Admin/Index.swift
Sources/PointFree/Auth.swift
Sources/PointFree/Episode/Episode.swift
Sources/PointFree/Routers/PointFreeRoutes.swift
Sources/PointFree/SiteMiddleware.swift
Sources/PointFree/Subscribe.swift
Sources/PointFree/TODO.swift

Updates all the dependencies, and updates middleware to properly understand tuples.
I have a bit of clean up I need to do, but need to step away for a bit. It's mostly all here tho.

Update dependencies and use new tuple stuff

---

Development.xcconfig
Makefile
Package.resolved
Package.swift
Sources/PointFree/Account/Cancel.swift
Sources/PointFree/Account/Team.swift
Sources/PointFree/Admin/Index.swift
Sources/PointFree/Emails/Mailgun.swift
Sources/PointFree/Footer.swift
Sources/PointFree/GoogleAnalytics.swift
Sources/PointFree/HighlightJs.swift
Sources/PointFree/LaunchSignup/Views.swift
Sources/PointFree/TODO.swift
Sources/Styleguide/DesignSystems/FlexGrid.swift
Sources/Styleguide/DesignSystems/Typography.swift

Got a lot of things that exponentially affect compile time :(

Start shaving off expression times

---

Package.resolved
Package.swift
Sources/PointFree/Account/Cancel.swift
Sources/PointFree/HtmlCssInliner.swift
Sources/PointFree/TODO.swift

Remove testables

---

Sources/PointFree/Account/ChangeSeats.swift

We want to render "2" as minimum when only one seat is taken.

Fix min change seats

---

.circleci/config.yml
.sourcery-templates/DerivePartialIsos.stencil
.travis.yml
Package.swift
Sources/PointFree/Admin/Index.swift
Sources/PointFree/Emails/NewEpisodeEmail.swift
Sources/PointFree/Environment.swift
Sources/PointFree/Episode/Episode.swift
Sources/PointFree/Episode/Show.swift
Sources/PointFree/Home.swift
Sources/PointFree/Routers/PointFreeRoutes.swift
Sources/PointFree/__Generated__/DerivedPartialIsos.swift
Sources/PointFreeTestSupport/MockEpisode.swift
Tests/PointFreeTests/EmailTests/NewEpisodeEmail.swift
Tests/PointFreeTests/EpisodeTests.swift

We'll manage episodes in the server layer.

Remove Transcripts Dependency

---

Sources/PointFree/Episode/Episode.swift

Need these initializers public to allow us to instantiate them elsewhere.

Make episode model public

---

Sources/PointFree/Stripe.swift

Another workaround for SR-6687

---

Sources/PointFree/Episode/Episode.swift
Sources/PointFree/Episode/Show.swift
Sources/PointFreeTestSupport/MockEpisode.swift

😅 Guess our streams don't work in Chrome! Here's a quick fix that allows us to specify additional source.

WebM support

---

Sources/PointFree/Admin/Index.swift
Sources/PointFree/Auth.swift
Sources/PointFree/GitHub.swift
Sources/PointFreeTestSupport/PointFreeTestSupport.swift

some people having probs logging in with email. just gonna send us some emails, and remove some things that have been problematic in the past

Send us an email on github auth failures.

---

Sources/PointFree/Tag.swift

Fix slug logic

---

Sources/PointFree/Newsletters.swift
Tests/PointFreeTests/__Snapshots__/NewslettersTests/testExpressUnsubscribe.2.Conn.txt

Just noticed that I used the error flash when express unsubscribing. better to use a notice.

Unsubscribing is not an error.

---

.PointFree.xccolortheme
Makefile
README.md

And installation instructions.

Add custom Xcode color theme

---

Makefile
README.md

Add ccmark modulemap to makefile.

---

.circleci/config.yml
.travis.yml
Makefile
OSS.xcconfig
Sources/PointFree/PublicEpisodes/0000-Introduction.swift
Sources/PointFree/PublicEpisodes/0001-Functions.swift
Sources/PointFree/PublicEpisodes/0002-SideEffects.swift
Sources/PointFree/PublicEpisodes/AllPublicEpisodes.swift
Sources/Server/main.swift

As we make episodes permanently public we should move them to this repo so that people can see them in local development. I also fixed #181 by making a separate OSS config.

Move public episodes to this repo

---

Tests/PointFreeTests/AccountTests/ChangeTests.swift

P simple. Should check our coverage in general on this stuff.

Add tests for upgrade invoicing

---

Sources/PointFree/Account/Invite.swift
Tests/LinuxMain.swift
Tests/PointFreeTests/InviteTests.swift
Tests/PointFreeTests/__Snapshots__/InviteTests/testAcceptInvitation_InviterHasCancelingStripeSubscription.1.Conn.txt

Let canceled subscribers join teams

---

Sources/PointFree/StripeHook.swift
Tests/PointFreeTests/StripeHookTests.swift
Tests/PointFreeTests/__Snapshots__/StripeHookTests/testStaleHook.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/StripeHookTests/testValidHook.1.Conn.txt

Round timestamp to int.

---

Package.swift
Sources/PointFree/Stripe.swift

- NIO request body fix
- Decode successful payments

Fixes for Stripe Hooks

---

Sources/PointFree/Account/Account.swift
Sources/PointFree/Account/Invite.swift
Sources/PointFree/Components.swift
Sources/PointFree/Emails/ChangeEmailConfirmation.swift
Sources/PointFree/Emails/EmailLayouts.swift
Sources/PointFree/Emails/InviteEmail.swift
Sources/PointFree/Emails/NewBlogPostEmail.swift
Sources/PointFree/Emails/NewEpisodeEmail.swift
Sources/PointFree/Emails/SharedEmailComponents.swift
Sources/PointFree/Episode/Show.swift
Sources/PointFree/Tag.swift

I keep forgetting to use the `text` helper, so I'm just converting all the old style to the new style.

Convert .text+encode to just text.

---

.gitmodules
Package.swift
Sources/PointFree/Bootstrap.swift
Sources/Runner/main.swift
Sources/Server/main.swift

Just a stub executable for now. But wanted to push this plumbing first.

Unify bootstrap logic and introduce Runner

---

Dockerfile
Sources/PointFree/Admin/Index.swift
Sources/PointFree/Emails/SendEmail.swift
Sources/Runner/main.swift

Just sending an email from `Runner/main.swift` that I'll hook up to a scheduler so we can see it work!

Try out a simple cron

---

.circleci/config.yml
.gitignore
.gitmodules
Makefile

A few more references to fix after the #229 shuffle.
Should help with #232

Fix transcript references

---

Sources/PointFree/Episode/Episode.swift
Tests/PointFreeTests/EpisodeTests.swift

Invert Boolean

---

.circleci/config.yml
.travis.yml
Dockerfile
Dockerfile.local
Makefile
README.md

Cleans up some of our OSS onboarding flow.

OSS Onboarding

---

Makefile

We deserve nice things, so cleaned up our private `make` command, too:
Also made it so `make` defaults to private if the transcript module is checked out, OSS otherwise.

Simplify Makefile usage

---

Sources/PointFree/Account/Change.swift
Sources/PointFree/Pricing.swift
Tests/PointFreeTests/AccountTests/ChangeTests.swift
Tests/PointFreeTests/AccountTests/__Snapshots__/ChangeTests/testChangeUpgradeIndividualMonthlyToTeamYearly.1.Conn.txt

Man this logic is gettin hairy.

Another upgrading gotcha

---

Sources/PointFree/__Generated__/DerivedPartialIsos.swift
Tests/LinuxMain.swift

Some tests weren't running on linux.

Run make sourcery

---

PointFree.playground/Pages/About.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Account.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Blog.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Database.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Email Tester.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Episode Page.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Homepage.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Invoices.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Router.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Subscribe.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Team Invites.xcplaygroundpage/Contents.swift

Clean up some playgrounds.

---

Package.swift

Updating a few more dependencies.

Update some dependencies.

---

Sources/PointFree/Blog/BlogPosts/AllBlogPosts.swift
Sources/PointFree/Blog/BlogPosts/BlogPost0007_OpenSourcingNonEmpty.swift
Sources/PointFree/Routers/GitHubRoutes.swift

PFP for tomorrow

---

Sources/PointFree/Blog/BlogPosts/BlogPost0007_OpenSourcingNonEmpty.swift

Fixed a few typos. Gonna leave this open for today to add any other corrections I find...

Fixed some typos in PFP0007.

---

Sources/PointFree/PublicEpisodes/0022-ATourOfPointFreeCo.swift
Sources/PointFree/PublicEpisodes/AllPublicEpisodes.swift

This episode's transcript can live in the OSS repo...

Make ep 22 public.

---

Sources/PointFree/PublicEpisodes/0022-ATourOfPointFreeCo.swift

Add missing correction

---

Sources/PointFree/Database.swift
Sources/PointFree/Tasks.swift
Tests/LinuxMain.swift
Tests/PointFreeTests/EmailTests/WelcomeEmailTests.swift

 Fix Linux Emails Segfault

---

Sources/PointFree/Tasks.swift

Just wanted to get some insight into how many emails of each bucket go out.

Add welcome email stats

---

Sources/PointFree/Pricing.swift
Tests/PointFreeTests/__Snapshots__/AuthTests/testHome_LoggedOut.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/HomeTests/testHomepage_LoggedOut.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PricingTests/testPricing.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PricingTests/testPricingLoggedIn_CanceledSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PricingTests/testPricingLoggedIn_NonSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PricingTests/testPricingLoggedIn_NonSubscriber_Expanded.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithHttps.3.0.0.0.0_allowed.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithHttps.4.127.0.0.0_allowed.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithHttps.5.localhost_allowed.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithWWW.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithWWW.2.Conn.txt

Less Strict Team Validation

---

Tests/LinuxMain.swift

Just updating our linux test file, its a lil out of date.

Add missing linux tests.

---

Sources/PointFreeTestSupport/PointFreeTestSupport.swift
Tests/PointFreeTests/AboutTests.swift

I know it'd be nice to somehow bake this into the strategy, but could be a nice stopgap till then.

Snap Helpers

---

Package.swift
Sources/PointFree/Atom.swift
Tests/PointFreeTests/__Snapshots__/AtomFeedTests/testAtomFeed.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/AtomFeedTests/testEpisodeFeed.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/AtomFeedTests/testEpisodeFeed_WithRecentlyFreeEpisode.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/BlogTests/testBlogAtomFeed.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/BlogTests/testBlogAtomFeed_Unauthed.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_InActiveSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_NonSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_Subscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_BadSalt.1.Conn.txt

Fixes https://github.com/pointfreeco/pointfreeco/issues/335 by using the work in https://github.com/pointfreeco/swift-web/pull/164.

Don't close the link tag in atom feeds.

---

Sources/PointFree/Blog/BlogPosts/AllBlogPosts.swift
Sources/PointFree/Blog/BlogPosts/BlogPost0022_SomeNewsAboutContramap.swift
Sources/PointFree/Blog/BlogPosts/BlogPost0023_OpenSourcingSnapshotTesting.swift
Sources/PointFree/PageLayout.swift
Tests/PointFreeTests/__Snapshots__/BlogTests/testBlogIndex.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/BlogTests/testBlogIndex_Unauthed.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/BlogTests/testBlogIndex_WithLotsOfPosts.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/BlogTests/testBlogShow.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/BlogTests/testBlogShow_Unauthed.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_HasCredits.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_UsedCredit.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodeCredit_PublicEpisode_NonSubscriber_UsedCredit.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodePageSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodePage_ExercisesAndReferences.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testFreeEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testFreeEpisodePageSubscriber.1.Conn.txt

I think this is ready to go for tomorrow except for the cover image. I'll use something from what you do for the readme.
I had to update some prism js stuff so that I could syntax highlight diffs.

Snapshot PFP

---

Sources/PointFree/VideoJs.swift
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_HasCredits.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_UsedCredit.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodeCredit_PublicEpisode_NonSubscriber_UsedCredit.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodePageSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodePage_ExercisesAndReferences.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testFreeEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testFreeEpisodePageSubscriber.1.Conn.txt

Support 1x, 1.25x, 1.5x, 1.75x and 2x.
Fixes #354

Support more video playback speeds.

---

Sources/PointFree/Pricing.swift
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedOut.1.Conn.txt

Just opening for posterity. Will merge when it's green.

Advent 2018

---

Sources/PointFree/Account/PrivateRss.swift
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_Subscriber.1.Conn.txt

Let's limit the RSS to 4 entries, not 4 weeks. That way when we skip a week it doesn't take away episodes.

Limit RSS to 4, not 4 weeks.

---

Sources/PointFree/Database.swift

Add "updated_at" to "feed_events"

---

Sources/PointFree/Database.swift

All right! Less chance to forget.

Add triggers to update row timestamps

---

Sources/PointFree/Footer.swift

Currently it's hardcoded to 2018...

Fix year in footer.

---

Sources/PointFree/Episode/Episode.swift
Sources/PointFree/Episode/Show.swift
Sources/PointFree/PublicEpisodes/References.swift
Tests/PointFreeTests/__Snapshots__/EpisodeTests/testEpisodePage_ExercisesAndReferences.1.Conn.txt

* Made a helper function that allows us to derive episode references from past episodes. Ideally there would be a special treatment for "related episodes", but for now we can just leverage the references section.
* Added a reference for railway oriented programming.

Prep work for episode 42

---

Sources/PointFree/PublicEpisodes/0004-AlgebraicDataTypes.swift

While reading through the transcript of this episode I noticed this sentence had an error in it.

Fix error in 004 transcript

---

Sources/PointFree/TODO.swift

The default is 60 seconds which is pretty long. So let's try this out.

Shorten the default timeout to 30 seconds.

---

Package.swift
Sources/GitHub/Client.swift
Sources/PointFree/Bootstrap.swift
Sources/PointFree/Environment.swift
Sources/PointFreePrelude/URLRequest.swift
Sources/Stripe/Client.swift

Broke during our modularization...

Fix Stripe Logging

---

.sourcery-templates/DerivePartialIsos.stencil
Makefile
Sources/PointFreeRouter/__Generated__/DerivedPartialIsos.swift
Tests/LinuxMain.swift

Just a few random things I found...

Small route clean up stuff.

---

.circleci/config.yml

- Xcode 10.1
- Don't bootstrap for CI
- Cache Homebrew

CircleCI Updates

---

.sourcery-templates/DerivePartialIsos.stencil
Sources/Database/Database.swift
Sources/GitHub/Client.swift
Sources/GitHub/Model.swift
Sources/GitHubTestSupport/Mocks.swift
Sources/Mailgun/Client.swift
Sources/Models/MailgunForwardPayload.swift
Sources/Models/Models.swift
Sources/Models/User.swift
Sources/PointFree/Auth.swift
Sources/PointFree/Bootstrap.swift
Sources/PointFree/Emails/RegistrationEmail.swift
Sources/PointFree/EnvVars.swift
Sources/PointFree/Newsletters.swift
Sources/PointFree/Session.swift
Sources/PointFree/StripeHtml.swift
Sources/PointFree/StripeWebhooks.swift
Sources/PointFree/TODO.swift
Sources/PointFreeRouter/GitHubRoutes.swift
Sources/PointFreeRouter/__Generated__/DerivedPartialIsos.swift
Sources/Stripe/Client.swift
Tests/PointFreeTests/AuthTests.swift
Tests/PointFreeTests/NewslettersTests.swift

A recent refactor almost led to a bug because we hadn't tagged things like our app secret and API keys. Luckily a snapshot test saved us, but let's make things even safer!

Tag Safely

---

Sources/PointFree/SiteMiddleware.swift
Sources/PointFreeRouter/Routes.swift
Sources/PointFreeRouter/__Generated__/DerivedPartialIsos.swift
Tests/PointFreeTests/StripeWebhooksTests.swift

A few have snuck in recently so let's start troubleshooting.

Add logging on unrecognized Stripe hooks

---

Sources/PointFree/Account/AccountRoutes.swift
Sources/PointFree/Bootstrap.swift
Sources/PointFree/RouteHelpers.swift
Sources/PointFree/SiteMiddleware.swift
Sources/PointFreeRouter/AdminRoutes.swift
Sources/PointFreeRouter/PointFreeRouter.swift
Sources/PointFreeRouter/Routes.swift
Sources/PointFreeRouter/__Generated__/DerivedPartialIsos.swift
Sources/PointFreeTestSupport/PointFreeTestSupport.swift
Sources/PointFreeTestSupport/TestCase.swift
Tests/PointFreeRouterTests/PointFreeRouterTests.swift

This allows us to bundle the base URL with the router in the `PointFreeRouter`, which will allow us to extract views into their own module more easily. Once that is done we'll work on a reader/context based way of threading base URL through the view.

Bundle base URL with the router in the PointFreeRouter module

---

Sources/PointFreePrelude/URLRequest.swift

This used to be `NSUnimplemented()`, but it's there now!

Use URLSession.shared

---

Sources/Models/PublicEpisodes/0001-Functions.swift

Not much more to say here. Keep up the good work. ✨

Small typo fix in public episode 0001-Functions

---

Sources/Models/PublicEpisodes/0002-SideEffects.swift

Small typo fix in public episode 0002-SideEffects

---

Sources/Models/BlogPosts/BlogPost0029_EnterpriseSubscriptions.swift
Sources/Models/BlogPosts/BlogPostXYZW_TODO.swift
Sources/PointFree/Blog/AllBlogPosts.swift

Blob post for enterprise subscriptions.

---

Sources/Logger/Logger.swift

Fix Logger levels

---

.circleci/config.yml
Makefile
Package.swift
PointFree.playground/Pages/Database.xcplaygroundpage/Contents.swift
Sources/Database/Database.swift
Sources/GitHub/Client.swift
Sources/PointFree/Account/Account.swift
Sources/PointFree/Enterprise.swift
Sources/PointFree/Newsletters.swift
Sources/PointFree/TODO.swift
Sources/PointFreePrelude/Concat.swift
Sources/PointFreePrelude/URLRequest.swift
Sources/PointFreeRouter/Routes.swift
Sources/PointFreeRouter/Util.swift
Sources/Views/Markdown.swift

This gets all dependencies, etc., in order so we can finally `rm` Xcode 10.1.

Xcode 10.2 Support

---

Sources/Stripe/Client.swift
Tests/StripeTests/StripeTests.swift
Tests/StripeTests/__Snapshots__/StripeTests/testRequests.fetch-coupon-bad-data.txt

Percent encode paths for stripe client.

---

Sources/Models/PublicEpisodes/AllPublicEpisodes.swift
Sources/PointFree/Episode/Show.swift
Sources/Views/EpisodeVideoView.swift
Sources/Views/TranscriptBlockView.swift
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_HasCredits.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_UsedCredit.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PublicEpisode_NonSubscriber_UsedCredit.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePageSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_ExercisesAndReferences.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePageSubscriber.1.Conn.txt

Vimeo Support

---

Sources/Models/BlogPosts/BlogPost0030_SwiftUIAndStateManagementCorrections.swift
Sources/Models/BlogPosts/BlogPost30_SwiftUIAndStateManagementCorrections.swift
Sources/Models/PublicEpisodes/0067-SwiftUIAndStateManagementPt3.swift
Sources/PointFree/Blog/AllBlogPosts.swift

I added a section about `Identifiable` and I moved the part 3 episode out of the private repo.

Blog post on SwiftUI corrections.

---

Sources/PointFree/Account/Cancel.swift
Sources/PointFree/AtomFeed.swift
Sources/PointFree/Blog/BlogAtomFeed.swift
Sources/PointFree/Emails/FreeEpisodeEmail.swift
Sources/PointFree/Emails/InviteEmail.swift
Sources/PointFree/Emails/RegistrationEmail.swift
Sources/PointFree/Emails/TeamEmails.swift
Sources/PointFree/Episode/Episode.swift
Sources/PointFree/RouteHelpers.swift
Sources/PointFree/SiteMiddleware.swift
Sources/PointFree/StripeWebhooks.swift
Sources/PointFree/SubscribeLanding.swift
Sources/PointFreeRouter/PointFreeRouter.swift
Sources/PointFreeRouter/Routes.swift
Sources/PointFreeRouter/__Generated__/DerivedPartialIsos.swift
Sources/Views/SubscribeLanding.swift
Tests/PointFreeTests/AuthTests.swift

Creates the route, middleware and view for the new pricing page.

Stubs for new pricing page

---

Sources/Views/PricingLanding.swift
Tests/PointFreeTests/__Snapshots__/PricingLandingTests/testLanding_LoggedIn_ActiveSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PricingLandingTests/testLanding_LoggedIn_InactiveSubscriber.1.Conn.txt

Been meaning to do this. Pretty straightforward, but I couldn't do one big container for the whole page since each module has a background that bleeds out of the margins. so I had to apply max width containers to each module.
Here's what it looks like when the browser is made bigger than the max width:

Adds a max width container to the pricing landing

---

Sources/Views/SubscriptionConfirmation.swift
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn.1.Conn.txt

A bug snuck into the latest pricing page changes that did not apply coupons correctly.

Fix subscribing with a coupon.

---

Sources/Models/PublicEpisodes/0000-Introduction.swift
Sources/Models/PublicEpisodes/0001-Functions.swift
Sources/Models/PublicEpisodes/0002-SideEffects.swift
Sources/Models/PublicEpisodes/0003-StylingWithFunctions.swift
Sources/Models/PublicEpisodes/0010-ATaleOfTwoFlatMaps.swift
Sources/Models/PublicEpisodes/0025-Zip-pt3.swift
Sources/Models/PublicEpisodes/0029-DSL-vs-TemplatingLanguages.swift
Sources/Models/PublicEpisodes/0041-TourOfSnapshotTesting.swift
Sources/Models/PublicEpisodes/0049-GenerativeArtPt1.swift
Sources/Models/PublicEpisodes/0050-GenerativeArtPt2.swift
Sources/Models/PublicEpisodes/0055-SwiftSyntaxCommandLineTool.swift
Sources/Models/PublicEpisodes/0065-SwiftUIAndStateManagementPt1.swift
Sources/Models/PublicEpisodes/0066-SwiftUIAndStateManagementPt2.swift
Sources/Models/PublicEpisodes/0067-SwiftUIAndStateManagementPt3.swift
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_InActiveSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_NonSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_Subscriber_Monthly.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_Subscriber_Yearly.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_BadSalt.1.Conn.txt

This updates a bunch of URLs to Vimeo.

More Vimeo Update

---

Tests/PointFreeTests/AccountTests/ChangeTests.swift
Tests/PointFreeTests/AccountTests/__Snapshots__/ChangeTests/testChangeRedirect.1.Conn.txt

https://trello.com/c/SaPdrVl1/375-write-test-for-redirecting-account-subscription-change-to-account

Add test for subscription/change redirect

---

Sources/PointFree/Account/AccountMiddleware.swift
Sources/PointFree/Account/UpdateProfile.swift
Sources/PointFree/Admin/AdminMiddleware.swift
Sources/PointFree/Admin/EpisodeCredit.swift
Sources/PointFree/Admin/FreeEpisodes.swift
Sources/PointFree/Admin/Ghost.swift
Sources/PointFree/Admin/Index.swift
Sources/PointFree/Admin/NewEpisodes.swift
Sources/PointFree/Admin/SendNewBlogPostMailer.swift
Sources/PointFree/Auth.swift
Sources/PointFree/Environment.swift
Sources/PointFree/PageLayout.swift
Sources/PointFree/Session.swift
Sources/PointFree/SiteMiddleware.swift
Sources/PointFreeRouter/AdminRoutes.swift
Sources/PointFreeRouter/PointFreeRouter.swift
Sources/PointFreeRouter/Routes.swift
Sources/PointFreeRouter/__Generated__/DerivedPartialIsos.swift
Sources/PointFreeTestSupport/PointFreeTestSupport.swift
Tests/PointFreeTests/AccountTests/AccountTests.swift
Tests/PointFreeTests/AccountTests/UpdateProfileTests.swift
Tests/PointFreeTests/AccountTests/__Snapshots__/UpdateProfileTests/testUpdateEmailSettings.1.Conn.txt
Tests/PointFreeTests/AccountTests/__Snapshots__/UpdateProfileTests/testUpdateExtraInvoiceInfo.1.Conn.txt
Tests/PointFreeTests/AccountTests/__Snapshots__/UpdateProfileTests/testUpdateNameAndEmail.1.Conn.txt
Tests/PointFreeTests/GhostTests.swift
Tests/PointFreeTests/InviteTests.swift
Tests/PointFreeTests/SessionTests.swift
Tests/PointFreeTests/SubscribeTests.swift

This gives admin the ability to ghost users (i.e. log in as them) so that we can debug things. When we do this a new cookie is saved that shows we are ghosting, and a large banner appears at the top of the screen so that we are aware of what we are doing.
I did some small refactors along the way, so will comment about that.

Ghosting 👻

---

Sources/FunctionalCss/GridHelpersUpgrade.swift
Sources/PointFree/PageLayout.swift
Sources/Views/About.swift
Sources/Views/Markdown.swift

Removes the underscores, unwraps a few arrays, and cleans up the about page.

Html Upgrade Tweaks

---

Sources/PointFree/Privacy.swift
Sources/Views/Privacy.swift
Sources/Views/TODO.swift

Upgrade Privacy HTML

---

Sources/PointFree/SubscribeConfirmation.swift
Sources/Views/SubscriptionConfirmation.swift
Sources/Views/TODO.swift
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedIn.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn_WithDefaults.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn_WithDefaults_OwnerIsNotTakingSeat.1.Conn.txt

Working with some of this HTML on the account page, so upgraded it.

Upgrade Subscribe Confirmation HTML

---

Sources/PointFree/PricingLanding.swift
Sources/Views/PricingLanding.swift
Tests/PointFreeTests/__Snapshots__/PricingLandingTests/testLanding_LoggedIn_ActiveSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PricingLandingTests/testLanding_LoggedIn_InactiveSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/PricingLandingTests/testLanding_LoggedOut.1.Conn.txt

Converting another page. Very straightforward.

Upgrade pricing land to new HTML lib.

---

Sources/Models/BlogPosts/BlogPostXYZW_0031_HigherOrderSnapshotStrategies.swift
Sources/Models/PublicEpisodes/References.swift
Sources/PointFree/Blog/AllBlogPosts.swift

Will deploy tonight so it's ready for tomorrow.

Higher-order snapshot strategy blog post

---

Makefile
PointFree.playground/Pages/Blog.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Database.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Email Tester.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Episode Page.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Homepage.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Invoices.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Router.xcplaygroundpage/Contents.swift
PointFree.playground/Pages/Team Invites.xcplaygroundpage/Contents.swift

This gets all the playgrounds building again.

Fix playgrounds

---

Package.swift
Sources/PointFreeRouter/AccountRoutes.swift
Sources/PointFreeRouter/AdminRoutes.swift
Sources/PointFreeRouter/ApiRoutes.swift
Sources/PointFreeRouter/GitHubRoutes.swift
Sources/PointFreeRouter/PartialIsoReflection.swift
Sources/PointFreeRouter/Routes.swift
Sources/PointFreeRouter/TwitterRoutes.swift

We can special case things rather than make the reflection method a one-size-fits-all thing.

Router Reflection Optimization

---

Sources/PointFree/Episode/Show.swift
Sources/PointFree/SiteMiddleware.swift
Sources/Views/EpisodeVideoView.swift
Tests/PointFreeTests/EpisodePageTests.swift
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_HasCredits.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_UsedCredit.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PublicEpisode_NonSubscriber_UsedCredit.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePageSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_ExercisesAndReferences.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_Trialing.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePageSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testProgress_LoggedIn.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testProgress_LoggedOut.1.Conn.txt

This ties together #564 and #566 by invoking the DB endpoint when the backend endpoint is called.

Invoke DB from backend endpoint.

---

Sources/PointFreeRouter/Routes.swift
Sources/Views/SubscriptionConfirmation.swift
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_5DollarsOff_Forever.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_5DollarsOff_Once.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_5DollarsOff_Repeating.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_PercentOff_Forever.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_PercentOff_Once.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_PercentOff_Repeating.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedOut.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedIn.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedIn_WithDiscount.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedOut.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn_WithDefaults.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn_WithDefaults_OwnerIsNotTakingSeat.1.Conn.txt

A student discount wasn't working. Should write a test for this but not sure this is the "ideal" fix. Can discuss tomorrow but gonna deploy this now.

Referral Codes Discount Fix

---

Package.swift

Fixes an issue @alexito4 brought up in #561.

Fix Package.swift to work in Xcode OSS

---

.github/workflows/ci.yml
README.md

Hopefully this is all that's needed.

Run GitHub Actions on PR

---

Sources/Models/Episode.swift
Sources/PointFree/Bootstrap.swift

This will allow us to move most of our episode data into the main repository.

Optionalize full episode videos

---

Sources/PointFree/Collections/CollectionIndex.swift
Sources/PointFree/SiteMiddleware.swift
Sources/PointFreeRouter/Routes.swift
Sources/Views/Collections/CollectionIndex.swift

Getting a simple, unstyled list of collections just so that it's easy to navigate around while testing. this will be updated with @amotion's new mockups soon

Collection index basics

---

Sources/Views/NewEpisodePage.swift

Just adds a link to the little timestamps here:

Link the timestamp in the chapters.

---

Dockerfile
Dockerfile.local

Already deployed, but for posterity: https://forums.swift.org/t/swift-5-1-5-for-linux/34478

Bump to 5.1.5

---

Sources/Database/Database.swift
Sources/DatabaseTestSupport/Mocks.swift
Sources/PointFree/Episode/Show.swift
Sources/Views/EpisodePage.swift
Sources/Views/EpisodeVideoView.swift
Tests/PointFreeTests/DatabaseTests.swift
Tests/PointFreeTests/EpisodePageTests.swift
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_WithEpisodeProgress.1.Conn.txt

We are now fetching the user's episode progress from the DB and using it to set the initial playhead time on the video.

Set video timestamp to user's episode progress.

---

Sources/Views/EpisodePage.swift
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePageSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_InCollectionContext.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_InCollectionContext_LastEpisode.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_Trialing.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_WithEpisodeProgress.1.Conn.txt

Good suggestion from @jpsim here: https://twitter.com/simjp/status/1262153043513991169

Link play icon on episode page

---

Sources/Stripe/Client.swift
Tests/StripeTests/__Snapshots__/StripeTests/testRequests.update-subscription.txt

This behavior regressed with Stripe API changes.

Fix Subscription Upgrade Behavior

---

Sources/PointFree/Account/PrivateRss.swift
Tests/PointFreeTests/PrivateRssTests.swift
Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_ValidUserAgent.1.Conn.txt

Just a quick PR to make sure we are tracking feed request events, even with an invalid user agent.

Properly track feed request events.

---

Sources/Stripe/Model.swift

Turns out country can be null!

Stripe card country can be optional

---

Sources/Models/Episodes/0058-WhatIsAParserPt3.swift

(Leftover from a previous study group session. 😄)

Small typo fix in 58.4.

---

Package.swift
Sources/Models/SubscriberState.swift
Sources/PointFree/Account/Invite.swift
Sources/Stripe/Model.swift

Makes it so that trial subscriptions are active.

Make trial subscriptions active.

---

Sources/Models/Collections/AllCollections.swift
Sources/Models/Collections/CaseStudies.swift
Sources/Models/Collections/Combine.swift
Sources/Models/Collections/SwiftUI.swift
Sources/Models/Episode.swift
Sources/Models/Episodes/0133-ConciseForms.swift
Sources/Models/Episodes/0134-ConciseForms.swift
Sources/Models/Episodes/0136-Animations.swift
Sources/Models/Episodes/0137-Animations.swift
Sources/Models/Episodes/References.swift

Create case studies collection.

---

Sources/Views/File.swift
Sources/Views/SubscriptionConfirmation.swift
Tests/PointFreeTests/DiscountsTests.swift
Tests/PointFreeTests/PricingLandingTests.swift
Tests/PointFreeTests/SubscribeConfirmationTests.swift
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_5DollarsOff_Forever.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_5DollarsOff_Once.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_5DollarsOff_Repeating.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_PercentOff_Forever.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_PercentOff_Once.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedIn_PercentOff_Repeating.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/DiscountsTests/testDiscounts_LoggedOut.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedIn.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedIn_ActiveSubscriber.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedIn_WithDiscount.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedOut.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_LoggedOut_ReferralCode.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testPersonal_ReferralCodeAndRegionalDiscount.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn_WithDefaults.1.Conn.txt
Tests/PointFreeTests/__Snapshots__/SubscribeConfirmationTests/testTeam_LoggedIn_WithDefaults_OwnerIsNotTakingSeat.1.Conn.txt

We were inaccurately displaying the subscription price for regional discounts with referrals.

Fix regional discount

---

Sources/Models/Episodes/0000-Introduction.swift

Added single letter to blurb to fix spelling mistake

Spelling Mistake fix

---

Package.swift
Sources/PointFree/AtomFeed.swift
Sources/PointFree/Environment.swift
Sources/PointFreeTestSupport/PointFreeTestSupport.swift

Should fix https://github.com/pointfreeco/pointfreeco/issues/711

Fix atom feed XML.

---

Dockerfile
Dockerfile.local
Package.swift
README.md
Sources/Views/Markdown.swift

Let's hold off till the official docker image is released. But I think otherwise we're good to go.

Prep for Swift 5.5

---

Sources/Models/BlogPosts/BlogPost0022_SomeNewsAboutContramap.swift

Thank you for share the idea. I think I am confused by the example.

Confusing in the sample code of `SomeNewsAboutContramap`

---

Sources/Models/Episode.swift
Sources/Models/Episodes/0174-ParserBuilders.swift
Tests/PointFreeTests/ApiTests.swift
Tests/PointFreeTests/__Snapshots__/ApiTests/testEpisode.1.Conn.txt

We should just switch over to use their API, but this will at least fix this week's ep :/

Temporary fix: new Vimeo URL format

---

Package.swift
Sources/Models/BlogPosts/BlogPost0075_URLVaporRouting.swift
Sources/PointFreeRouter/AccountRoutes.swift
Sources/PointFreeRouter/AdminRoutes.swift
Sources/PointFreeRouter/ApiRoutes.swift
Sources/PointFreeRouter/GiftRoutes.swift
Sources/PointFreeRouter/GitHubRoutes.swift
Sources/PointFreeRouter/PointFreeRouter.swift
Sources/PointFreeRouter/Routes.swift
Sources/PointFreeRouter/TwitterRoutes.swift
Sources/PointFreeTestSupport/PointFreeTestSupport.swift

A few blog tweaks and updates to use the official URL Routing package.

URL Routing updates

---

Sources/Models/Collections/ComposableArchitecture.swift

Fix typo in the Composable Architecture collection's Testing section

---

Sources/Models/BlogPosts/BlogPost0084_SwiftUINavRelease.swift

Fix typo in post for SwiftUINavigation release

---

Package.resolved
Package.swift
Sources/Database/Database.swift
Sources/PointFree/About.swift
Sources/PointFree/SiteMiddleware.swift
Sources/PointFreePrelude/Tuple.swift
Sources/PointFreeTestSupport/TestCase.swift
Sources/Runner/main.swift
Sources/Server/main.swift
Tests/PointFreeTests/AccountTests/AccountTests.swift
Tests/PointFreeTests/AccountTests/ChangeTests.swift
Tests/PointFreeTests/AccountTests/UpdateProfileTests.swift
Tests/PointFreeTests/ApiTests.swift
Tests/PointFreeTests/AppleDeveloperMerchantIdDomainAssociationTests.swift
Tests/PointFreeTests/AuthTests.swift
Tests/PointFreeTests/DatabaseTests.swift
Tests/PointFreeTests/EitherIOTests.swift
Tests/PointFreeTests/EmailTests/WelcomeEmailTests.swift
Tests/PointFreeTests/EpisodePageTests.swift
Tests/PointFreeTests/GhostTests.swift
Tests/PointFreeTests/InviteTests.swift
Tests/PointFreeTests/NewslettersTests.swift
Tests/PointFreeTests/SubscribeTests.swift

Updates to use async-compatible versions of swift-prelude and swift-web.

Async compatibility

---

Sources/Views/EpisodePage.swift

Fixes this issue: https://twitter.com/tomassliz/status/1616155366424707100

Don't use non-breaking space after comma.

---

Sources/Models/BlogPosts/BlogPost0094_ModernSwiftUIPart1.swift

Fix the data source of ForEach in Modern SwiftUI Part 1

---

Sources/Models/Episodes/0221-PFLive-DependenciesStacks.swift

fix typo in pf live script

---

Sources/PointFree/AtomFeed.swift
Sources/PointFree/SiteMiddleware.swift
Sources/PointFreeRouter/Routes.swift
Tests/PointFreeTests/AtomFeedTests.swift
Tests/PointFreeTests/__Snapshots__/AtomFeedTests/testSlackFeed.1.Conn.txt

A special feed for Slack that is simpler than our normal episode feeds.

Special RSS feed for Slack.

---

Sources/Stripe/Model.swift
Sources/Views/Account/Account.swift

I had a typo in the new subscription status.

Fix Stripe decoding

---

Package.resolved

We got a low dependabot alert that's resolved by upgrading our dependencies, so let's bump things assuming all is green.

Bump package dependencies

---

Sources/Transcripts/Resources/0243.md

I corrected a simple typo. Look forward to the next episode! 😄

Fix a typo in ep.243

---

Sources/Views/PricingLanding.swift
Sources/Views/SubscriptionConfirmation.swift

Just needed to thread through the subscription data to a few more spots in order to have the "Regional discount" link attach the referral credit.

Support regional discount and referral credit.

---

Sources/Transcripts/BlogPosts/BlogPost0119.md

Hi, I saw this in the blog post and thought I would make a PR to help out.

Fix blog post

---

Sources/Transcripts/BlogPosts/BlogPost0126.md

Jus’ lookin’ out — cheers to an amazing year of Point-Free! 🎉

Small typo fixes for 2023 year in review.

---

Sources/PointFree/Webhooks/SubscriptionsWebhook.swift
Tests/PointFreeTests/__Snapshots__/HomeTests/testHomepage_Subscriber.1.Conn.txt

Just to give a little more insight when a larger team or longtime subscriber churns.

Churn admin email
