Sources/PointFree/Routes.swift, Tests/PointFreeTests/SiteMiddlewareTests.swift, Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithWWW.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithWWW.2.Conn.txt, Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithoutHeroku.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithoutHeroku.2.Conn.txt, Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithoutWWW.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/SiteMiddlewareTests/testWithoutWWW.2.Conn.txt
it seems that checking the url scheme for `https` cannot be trusted in heroku and instead we must check a header: https://jaketrent.com/post/https-redirect-node-heroku/
=> proper redirects for heroku

Sources/PointFree/LaunchSignup/Airtable.swift
it seems that when you don't use `URLSession.shared` (which isn't in linux foundation) you gotta clean up yer session afterwards else you leak memory :/
doing this manually now but we could have an `IO` helper to make this better too...
=> Fix memory leak when dealing with URLSession

.gitignore, Sources/PointFree/EnvVars.swift, Tests/PointFreeTests/__Snapshots__/AuthTests/testLogin.1.Conn.txt
This will first try to load env vars from `.env` locally, and if that fails fallback to `ProcessInfo.processInfo.environment`. It should allow us to control the environment locally while keeping our true secrets only on the server.
=> Move env vars to .env

Sources/PointFree/GitHubApi.swift, Sources/PointFree/LaunchSignup/Airtable.swift, Tests/PointFreeTests/AuthTests.swift, Tests/PointFreeTests/TestCase.swift
Not sure if you prefer the explicitness of the mock names. If so we could still simplify the implementations, _e.g._:
``` swift
func mockFetchAuthToken(
result: Either<Prelude.Unit, GitHubAccessToken>
)
-> (String)
-> EitherIO<Prelude.Unit, GitHubAccessToken> {
return result |> pure >>> const
}
```
They'd both have the same implementation, though!
=> Fun test stub cleanup using function composition

Sources/PointFree/Routes.swift, Sources/PointFree/SiteMiddleware.swift
I've done this a few times in experimental branches, so just doing it once and for all. 
I just wanted the routes to be in its own file, and the site's middleware to be in another. makes it easier to see how to add new routes.
=> Move middleware to its own file

CC-LICENSE, LICENSE, README.md
We can use a creative commons license for the content of the site (images, copy, etc...) and use an MIT license for the actual code.
=> CC license for content, MIT for code

Sources/PointFree/HtmlCssInliner.swift, Tests/PointFreeTests/HtmlCssInlinerTests.swift, Tests/PointFreeTests/__Snapshots__/HtmlCssInlinerTests/testHtmlCssInliner.1.html
A simple way of inlining a stylesheet's styles into an html document! This is not a full solution as we do not attempt to match _any_ kind of selector to a node, however it works beautifully with the stylesheets that we care most about.
I have a test that shows a good use case, but here it is for posterity:
```swift 
let stylesheet =
body % fontSize(.px(16))
<> p % color(.black)
<> "#hero" % maxWidth(.pct(100))
<> "#some-id" % backgroundColor(.red)
<> ".p1" % padding(all: .px(16))
<> ".bold" % fontWeight(.bold)
<> ".leading" % fontSize(.px(18))
<> (body | html) % height(.pct(100))
<> ("#footer" | footer | ".footer") % display(.block)
let doc = document([
html([
body([
div([id("hero")], [
h1(["Point-Free"])
]),
p([Html.`class`("p1")], [
"This p tag gets styles from the tag element and …
```
=> Css style inliner

Sources/PointFree/Bootstrap.swift, Sources/PointFree/Emails/Mailgun.swift, Sources/PointFree/Emails/SendEmail.swift, Sources/PointFree/TODO.swift, Tests/PointFreeTests/EitherIOTests.swift
This started from me investigating what we'd need to do to support a `List-Unsubscribe` header in our emails. One component of it is for us to main a "mailgun route" for each of our newsletter types so that we can forward a reply to "unsubscribe-newsletter@pointfree.co" to our server, and then we handle the response.
Then that led me to wanting to synchronize those routes on mailgun via their API with the cases in our enum.
Then that led me to wanting to have a bootstrap function that runs when the server first boots up.
But we already have something like that in `pointfreeco-server` for starting up postgres.
So, I just made a general bootstrap function that can be called from the server. This is the place I would add that route synchronization stuff once I get to it.
Whatdya think?
=> Bootstrap function for starting up the site.

Package.swift
It seems that https://github.com/vapor/postgresql no longer exists, and instead we should point to https://github.com/vapor-community/postgresql ¯\_(ツ)_/¯
=> Update postgres package to point to community package.

Makefile
When running `make` I get the following error:
```
make: *** No rule to make target `commoncrypto-mm', needed by `bootstrap'.  Stop.
```
Turns out there was a typo in the `Makefile`.
=> No rule to make target `commoncrypto-mm'

Dockerfile
I just deployed and momentarily brought down the site... oops!
I found this in the logs:
```
2018-02-26T01:42:45.558032+00:00 app[web.2]: /bin/sh: 1: ./.build/release/pointfreeco: not found
```
and realized there was another server reference I didn't change in #164
=> Fix Docker command

Sources/PointFree/StripeHook.swift
This should allow us to better troubleshoot any signature validation issues.
=> Add debug info to Stripe Hook signature failures

Sources/PointFree/About.swift, Sources/PointFree/Blog/BlogPost.swift, Sources/PointFree/Environment.swift, Sources/PointFree/FeatureFlags.swift, Sources/PointFree/Session.swift, Sources/PointFreeTestSupport/PointFreeTestSupport.swift, Tests/PointFreeTests/BlogTests.swift
Just moving ancillary stuff out of `Environment.swift` and leaning more on the initializer for `Environment` we get for free.
=> Environment.swift clean up

Sources/PointFree/Blog/BlogPosts/BlogPost0014_AnnouncingValidated.swift
This makes sure we use each specific validator for each example, rather than using the `id` validator each time.
=> Use correct validators for example

Tests/PointFreeTests/AccountTests/AccountTests.swift, Tests/PointFreeTests/AccountTests/ChangeTests.swift, Tests/PointFreeTests/AccountTests/PaymentInfoTests.swift, Tests/PointFreeTests/BlogTests.swift, Tests/PointFreeTests/EpisodeTests.swift, Tests/PointFreeTests/HomeTests.swift, Tests/PointFreeTests/InvoicesTests.swift, Tests/PointFreeTests/NotFoundMiddlewareTests.swift, Tests/PointFreeTests/PricingTests.swift, Tests/PointFreeTests/PrivacyTests.swift
Speeds up the test runner a bit since we're not creating a new IO for every web view snap.
=> Use assertSnapshots helper

Sources/PointFree/Account/PrivateRss.swift, Tests/PointFreeTests/PrivateRssTests.swift, Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_Subscriber.1.Conn.txt
Removing that `Private Rss Feed Error` email cause I think we know what is going on there. Also I'm now exposing all episodes in the private RSS feed. Seems maybe not worth doing what we are doing to combat fraudulent activity. Thoughts?
=> Remove error email and expose all episodes in RSS.

Dockerfile, Dockerfile.local
For posterity, there are some Linux Foundation bugs that were fixed in Swift 4.1, regressed in Swift 4.2, and then fixed in 4.2.1 :/
Today we took down subscriptions for a few minutes because we deployed to Swift 4.2.
=> Deploy to Swift 4.2.1

Package.swift, Sources/PointFree/GitHub.swift, Tests/PointFreeTests/__Snapshots__/GitHubTests/testRequests.fetch-auth-token.URLRequest.txt
=> Swift 4.2.1

Sources/PointFree/PublicEpisodes/References.swift
I was reminded that @cbarrett's talk was the inspiration for the first version we tried at Kickstarter! I'll add the links to the transcripts repo once merged.
=> Add "Structure and Interpretation of Swift Programs" reference

Sources/PointFree/Account/PrivateRss.swift
We were getting compiler crashes when deploying, and this fixes it somehow. I have a feeling it's only the generic in the `trackFeedRequest` middleware, but I'm going to go ahead and leave the other stuff too.
=> Work around for swift compiler bug.

Sources/PointFree/SiteMiddleware.swift
Now that we have a proper timeout in the API climate let's drop this timeout until we have a better way to cleanup resources.
=> Drop timeout for now.

Sources/PointFreePrelude/URLRequest.swift
Just curious if this matters at all.
Starting to think maybe we bring back the `requestTimeout` middleware transformer...
=> Set timeout on URLRequest too.

Sources/PointFreeRouter/AccountRoutes.swift, Sources/PointFreeRouter/AdminRoutes.swift, Sources/PointFreeRouter/Routes.swift, Sources/PointFreeRouter/Util.swift
I wanted to play around with ideas of avoiding the `>>>` for very general partial isos, like the `.tagged` one. I think this reads pretty nicely. What do you think?
Also, it was great having the router in a module to test this. Instant compile times!
=> Another way of doing tagged values in routes.

.circleci/config.yml
Removes 5 minutes from circle CI build times. I added it a few months ago to fix some weird circle problems, but seems to be ok now!
=> Remove brew upgrade step.

Sources/Views/EpisodeVideoView.swift, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_HasCredits.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_UsedCredit.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PublicEpisode_NonSubscriber_UsedCredit.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePageSubscriber.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_ExercisesAndReferences.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePage.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePageSubscriber.1.Conn.txt
@krzyzanowskim [brought](https://twitter.com/krzyzanowskim/status/1146355372342611969) it to my attention that videos don't play inline on mobile. We use the `playsinline` attribute on the `video` tag, but apparently video.js overrides that, so I add to also add it to the video.js config.
=> Fix inline video.

Sources/Syndication/Rss.swift
XML is more strict than HTML, so we need to escape `&` to `&amp;` even in attributes.
=> Escape podcast 

Sources/Models/PublicEpisodes/0065-SwiftUIAndStateManagement.swift
Xcode 11 beta 4 has changed the `BindableObject` API so I'm just adding some correction blocks to ep 65 and I've fixed the episode code sample.
=>  Correct didChange vs willChange.

Sources/Models/SubscribeConfirmationData.swift, Sources/PointFree/SiteMiddleware.swift, Sources/PointFree/SubscribeConfirmation.swift, Sources/Views/SubscriptionConfirmation.swift
https://trello.com/c/r2kxgFLV/373-subscribeconfirmation-route-should-not-use-subscribedata
=> Simplify Subscribe Confirmation Data

Sources/PointFree/Account/Account.swift
This bug caused the "Add teammate" module to not show for people on the old subscription plans.
=> Compute cost of adding teammate differently.

Sources/Database/Database.swift
I think this is just something we overlooked a long time ago. The users table `subscription_id` wasn't an actual foreign key pointing to `subscriptions.id`. This is never really problematic in production because we never delete subscriptions from the table, but it's still nice to have this constraint, and it can be useful for local development when messing with data manually.
https://trello.com/c/OFf9g5Qk
=> Add a foreign key for user's subscription id.

Sources/PointFree/StripeWebhooks.swift, Tests/LinuxMain.swift, Tests/PointFreeTests/StripeWebhooksTests.swift, Tests/PointFreeTests/__Snapshots__/StripeWebhooksTests/testNoInvoiceSubscriptionId.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/StripeWebhooksTests/testNoInvoiceSubscriptionId_AndNoLineItemSubscriptionId.1.Conn.txt
Turns out many stripe hooks come with invoices that don't have subscriptions attached. For those we can search the invoice line items to find the subscription.
=> Fix stripe webooks for invoices without subscription ids.

Sources/Database/Database.swift, Sources/PointFree/StripeWebhooks.swift
We're getting a weird web hook failure that doesn't have any error messaging because the error is erased to `Unit`. I'm adding some more logging so that we can debug this.
=> More webhook failure messaging.

Sources/PointFree/Subscribe.swift, Tests/PointFreeTests/__Snapshots__/SubscribeTests/testHappyPath_Team.2.txt, Tests/PointFreeTests/__Snapshots__/SubscribeTests/testHappyPath_Team_OwnerIsNotTakingSeat.2.txt
While working on the subscribe stuff for #498 I was seeing that the subscribe middleware could be slightly simplified. First, it could be flattened by not starting off with a pure `EitherIO` value. Then, I believe we should first create the subscription in the DB and _then_ try sending out the invites. Otherwise an error in sending emails will mess up creating the DB row. Also, I think sending the invites shouldn't result result in any errors, i.e. if an email fails to send it shouldn't cause any errors to show.
=> Slight simplification to subscribe logic.

Makefile
Leaving out an override (for now), since we can merely run the Heroku commands from scratch if we really need to. This will blow up on `make deploy-production` if the working directory is dirty (with tracked or untracked changes), or if local `master` and `origin/master` are not in sync.
=> (Deployment) Precautions

.circleci/config.yml, .gitignore, Sources/PointFree/Subscribe.swift
I just wanted to do the bare minimum to get Xcode 11 support in. I'm not deleting the Xcode project or anything. It would be great to figure out how to continue using playgrounds. Even if SwiftUI previews can help us eventually, there's still some good use cases for playgrounds (like playing with the database or router).
=> Bare minimum to support Xcode 11

Sources/PointFree/StripeWebhooks.swift, Sources/Stripe/Model.swift, Sources/Views/Account/Invoices.swift, Tests/PointFreeTests/StripeWebhooksTests.swift, Tests/PointFreeTests/__Snapshots__/StripeWebhooksTests/testNoInvoiceNumber.1.Conn.txt
With the Stripe API came new hooks delivered for subscription creation failures. We can ignore them for now.
=> Ignore new Stripe hook failures

Dockerfile.local, Sources/Models/BlogPosts/BlogPost0011_SolutionsToZipExercisesPt1.swift, Sources/Stripe/Model.swift
A couple low-hanging optimizations. Middleware chains are the primary offender for our build times, but I'm not sure if there's any easy way of cleaning those up without untangling a lot of types.
=> Coupla build speed-ups

.github/workflows/ci.yml, Package.swift
Just wanted to wrap up a quick exploration from this morning to restore warnings when editing Point-Free as a Swift package and not an Xcode project.
=> Add slow type checking warnings to SPM package

Sources/PointFree/Session.swift, Tests/PointFreeTests/AccountTests/AccountTests.swift, Tests/PointFreeTests/AuthTests.swift, Tests/PointFreeTests/DiscountsTests.swift, Tests/PointFreeTests/EnterpriseTests.swift, Tests/PointFreeTests/InviteTests.swift, Tests/PointFreeTests/PricingLandingTests.swift, Tests/PointFreeTests/PrivateRssTests.swift, Tests/PointFreeTests/SubscribeConfirmationTests.swift, Tests/PointFreeTests/SubscribeTests.swift
(NB: This is based off of #559)
Just like middlewares, some tests take awhile to build do to the way we configure the environment. This flattens things to just use plain mutation. Some things are messier this way. It would be worth seeing if we can regain the ergonomics by using overture while still keeping compile times down.
=> Speed up a bunch of test compilation times.

Sources/Models/Episode.swift, Sources/Models/PublicEpisodes/0000-Introduction.swift, Sources/Models/PublicEpisodes/0001-Functions.swift, Sources/Models/PublicEpisodes/0002-SideEffects.swift, Sources/Models/PublicEpisodes/0003-StylingWithFunctions.swift, Sources/Models/PublicEpisodes/0004-AlgebraicDataTypes.swift, Sources/Models/PublicEpisodes/0010-ATaleOfTwoFlatMaps.swift, Sources/Models/PublicEpisodes/0029-DSL-vs-TemplatingLanguages.swift, Sources/PointFree/ApiMiddleware.swift, Sources/PointFree/AtomFeed.swift, Sources/Views/EpisodeVideoView.swift
We were only missing trailers on ep0 (which is a trailer in itself) and ep1, so I'm thinking the safest way to move non-full-video data into the main repo is to make `fullVideo` optional and cascade down to `trailerVideo` when in OSS mode.
=> Require Episode Trailers

Sources/Models/Episode.swift
This doesn't seem to be used, so just removing for now.
=> Remove lesson blurb.

Sources/Views/Collections/CollectionSection.swift, Tests/PointFreeTests/__Snapshots__/CollectionsTests/testCollectionSection.1.Conn.txt
The simplest thing we can do to get the alignment right. I think some of the surrounding markup could be simplified too. I sketched how a basic version could look here: https://jsfiddle.net/bq3st5wL/1/
=> Fix long collection names on mobile.

Sources/Models/Collections/Parsing.swift, Sources/Models/Episode.swift, Sources/Views/Collections/CollectionSection.swift, Tests/ModelsTests/CollectionTests.swift
I was able to figure out the cyclical references in our collections. We needed to make the related content lazy _and_ we need to make the parsing collection a computed `var` instead of a `let`.
That causes a bunch of whitespace differences so you may want to view this diff without whitespace.
=> Make collection references lazy so that we can do cyclical references.

Sources/PointFree/Admin/NewEpisodes.swift
This will speed things up a bit. We could speed it up a bit more if we ran a few in parallel rather than one after the other. I thought there were rate limits, but it doesn't seem like that's the case anymore, or maybe it never was...
=> Remove email delay.

Sources/Stripe/Client.swift, Tests/StripeTests/__Snapshots__/StripeTests/testRequests.fetch-invoices.txt
The interface can be confusing when void and failing invoices show up.
=> Filter invoices to paid

Sources/Models/Episodes/0099-ErgonomicStateManagementPt2.swift
Also, in session, we landed on this solution and were wondering if it’s equally as valid—or, would moving the index out as a top-level parameter cause issues for call sites?
```swift
extension Reducer {
func indexed<GlobalValue, GlobalAction, GlobalEnvironment>(
value: WritableKeyPath<GlobalValue, [Value]>,
action: CasePath<GlobalAction, Action>,
environment: @escaping (GlobalEnvironment) -> Environment,
index: Int
) -> Reducer<GlobalValue, GlobalAction, GlobalEnvironment> {
pullback(
value: value.appending(path: \.[index]),
action: action,
environment: environment
)
}
}
```
=> Re-work #99.2’s solution to compile.

Dockerfile, Dockerfile.local, Sources/PointFree/RunnerTasks/WelcomeEmails.swift
TIL Heroku schedulers will run the entrypoint of a Dockerfile, which will take precedence over the command it was configured with.
=> Fix Docker for Heroku

Sources/Models/Episode.swift, Sources/Models/Episodes/0100-ATourOfTheComposableArchitecturePt1.swift, Sources/ModelsTestSupport/MockEpisode.swift, Tests/PointFreeTests/__Snapshots__/ApiTests/testEpisode.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/AtomFeedTests/testAtomFeed.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/AtomFeedTests/testEpisodeFeed.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/AtomFeedTests/testEpisodeFeed_WithRecentlyFreeEpisode.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_HasCredits.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_NoCredits.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_UsedCredit.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PublicEpisode_NonSubscriber_UsedCredit.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePageSubscriber.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_ExercisesAndReferences.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_InCollectionContext.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_InCollectionContext_LastEpisode.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_Trialing.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_WithEpisodeProgress.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePage.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePageSubscriber.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_Subscriber_Monthly.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_Subscriber_Yearly.1.Conn.txt
It's always a lil annoying to figure out the URLs for the streaming and download sources, so I've updated the `Episode.Video` model to hold the Vimeo data and the construct the url's under the hood.
For now I've made this backwards compatible so that we don't have to convert all 200+ videos now.
=> Make Video model aware of vimeo id and secret.

Sources/PointFree/Admin/SendNewBlogPostMailer.swift
We removed this delay from sending new episode emails (#643) but not blog posts...
=> Remove delay from sending blog emails.

Sources/Models/Collections/Randomness.swift
Currently we have generative art episodes in the related section, but seems to make more sense as a dedicated section of the collection. not sure why we did it like that.
=> Add generative art to randomness collection.

Sources/PointFree/Episode/Show.swift, Sources/Views/EpisodePage.swift, Tests/ModelsTests/EpisodeTests.swift, Tests/PointFreeTests/EpisodePageTests.swift, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_HasCredits.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_NoCredits.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PrivateEpisode_NonSubscriber_UsedCredit.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodeCredit_PublicEpisode_NonSubscriber_UsedCredit.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePageSubscriber.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePageSubscriber_Deactivated.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_ExercisesAndReferences.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_InCollectionContext.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_InCollectionContext_LastEpisode.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_Trialing.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testEpisodePage_WithEpisodeProgress.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePage.1.Conn.txt, Tests/PointFreeTests/__Snapshots__/EpisodePageTests/testFreeEpisodePageSubscriber.1.Conn.txt
I just realized that links in the blurb are rendered dark even though they are on a dark background. This is just a quick fix to make it light.
=> Change blurb link to white on episode page

Sources/Models/Episodes/0149-DerivedBehavior.swift
small typo "we will will build" should be "we will build"
=> Update 0149-DerivedBehavior.swift to remove repeated word in description

Sources/PointFreeTestSupport/TestCase.swift, Sources/Views/Account/Account.swift, Tests/PointFreeTests/AccountTests/__Snapshots__/AccountTests/testAccountWithCredit.1.Conn.txt, Tests/PointFreeTests/AccountTests/__Snapshots__/AccountTests/testAccountWithFlashError.1.Conn.txt, Tests/PointFreeTests/AccountTests/__Snapshots__/AccountTests/testAccountWithFlashNotice.1.Conn.txt, Tests/PointFreeTests/AccountTests/__Snapshots__/AccountTests/testAccountWithFlashWarning.1.Conn.txt, Tests/PointFreeTests/AccountTests/__Snapshots__/AccountTests/testAccountWithPastDue.1.Conn.txt, Tests/PointFreeTests/AccountTests/__Snapshots__/AccountTests/testTeam_NoRemainingSeats.1.Conn.txt
I realized we don't require the email for inviting a teammate which makes it easy to accidentally hit the button and get charged. Making it required gives us a little bit of validation before it is submitted.
=> Require email for teammate invite.

Sources/Models/BlogPosts/BlogPost0010_StudentDiscounts.swift
On [Announcing Student Discounts](https://www.pointfree.co/blog/posts/10-announcing-student-discounts) page, it is written that a discount code for `individual` subscription plan will be given, but on [Pricing](https://www.pointfree.co/pricing) page, there's no `individual` plan.
I don't know when, but the name of the plan seems to be changed from `individual` to `personal`.
To be precise, I update the words.
=> Update subscription plan (individual → personal) of Student Discounts page

Sources/PointFree/Account/Cancel.swift, Sources/Stripe/Model.swift, Sources/Views/Account/Account.swift, Sources/Views/Account/Invoices.swift
The value can be `null`, so let's be honest about it and generous about decoding.
=> Make Stripe plan description optional

Package.resolved, Package.swift, Sources/PointFree/About.swift, Sources/PointFree/Account/Account.swift, Sources/PointFree/Account/AccountMiddleware.swift, Sources/PointFree/Account/Cancel.swift, Sources/PointFree/Account/PrivateRss.swift, Sources/PointFree/AtomFeed.swift, Sources/PointFree/Auth.swift, Sources/PointFree/Emails/SendEmail.swift, Sources/PointFree/PageLayout.swift, Sources/PointFree/Session.swift, Sources/PointFree/SiteMiddleware.swift, Tests/PointFreeTests/AccountTests/__Snapshots__/CancelTests/testCancelNoSubscription.1.Conn.txt, Tests/PointFreeTests/AccountTests/__Snapshots__/CancelTests/testReactivateNoSubscription.1.Conn.txt, Tests/PointFreeTests/PrivateRssTests.swift, Tests/PointFreeTests/__Snapshots__/PrivateRssTests/testFeed_Authenticated_Subscriber_Yearly_StripeDown.1.Conn.txt
I ported many of our IO middleware helpers over to `Conn` in an effort to make refactoring existing endpoints easier: https://github.com/pointfreeco/swift-web/commit/a33fcffb1de6dc23bcb5eeb494bbc000f2a80807
This PR exercises this ability to disentangle a couple endpoints: the About page (which is simple), and the private RSS endpoints (which was pretty complex).
=> Try out new `Conn` helpers

Package.resolved, Package.swift
Came across [this](https://forums.swift.org/t/asynchttpclient-crlf-injection-in-http-request-headers-cve-2023-0040/62604) today and so updating. Even though our Package.swift was set to 0.9.0 we were technically already using 0.13.1 according to our resolve file, so I just went ahead and bumped to 0.13.2.
=> Update AsyncHTTPClient to 0.13.2

.pf-env.example, Sources/Models/BlogPosts/BlogPost0100_Anniversary.swift, Sources/PointFree/EnvVars.swift, Sources/PointFree/SiteMiddleware.swift, Sources/PointFreeRouter/Routes.swift, Tests/PointFreeTests/EnvVarTests.swift, Tests/PointFreeTests/__Snapshots__/EnvVarTests/testDecoding.1.txt
Seems like it may expire sometimes, so easier to maintain the link if we move it to env vars.
=> Move Slack invite URL to env var

Sources/PointFree/Auth.swift, Sources/PointFree/Emails/SendEmail.swift, Sources/PointFree/SiteMiddleware.swift, Tests/PointFreeTests/AuthTests.swift, Tests/PointFreeTests/__Snapshots__/AuthTests/testAuth_WithRegisterUserFailure.1.Conn.txt
A common login error occurs for users with multiple GitHub accounts associated with the same primary email address, either because they've deleted and recreated their GitHub account, or from work accounts clashing with home accounts, etc. This PR checks for this issue and surfaces a better error message to users.
=> Better messaging for login errors

Sources/Database/Live.swift, Tests/PointFreeTests/AccountTests/AccountTests.swift
If a team subscription owner has two subscriptions, a past cancelled one and a current active one, then the teammates on the old subscription will show up on the team page of the new one. We will stop showing them on that page to make it clear that they need to be invited to the new subscription to regain access.
=> Fix teammates query.

Sources/StyleguideV2/HTML/HTMLInlineStyle.swift
My last PR (#925) computed the index of class names incorrectly. After inserting a class into the set it then used the set count for the index, but it should have been 1 less.
=> Fix index of inline style classes.

Sources/Views/GiftsV2.swift
The page https://www.pointfree.co/gifts has a typo, which this PR fixes.
=> Fixed a typo 'momths' to 'months'

Package.resolved, Package.swift
Update links for repositories moved to the swiftlang org on GitHub
+ Package.resolved
+ Package.swift
Correct the link:
+ https://github.com/apple/swift-cmark => https://github.com/swiftlang/swift-cmark
+ https://github.com/apple/swift-markdown => https://github.com/swiftlang/swift-markdown
+ https://github.com/apple/swift-syntax => https://github.com/swiftlang/swift-syntax
=> Update swiftlang repository link for Package.swift and Package.resolved

Sources/PointFree/Account/Account.swift, Sources/PointFree/Auth.swift, Tests/PointFreeTests/AuthTests.swift
Yesterday log in was broken for awhile on Point-Free because the Stripe API was having problems, and we refresh the user's subscription state when they log in. Let's not prevent log in if Stripe is having problems. Also let's refresh the user's subscription state when they visit their account page.
=> Don't fail login if Stripe is having problems.
